SELECT (MAX(GL_DR.SUM_AMOUNT) - MAX(GL_CR.SUM_AMOUNT)) OPEN_WIP, GLT.WOO_AUTO_KEY

FROM

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'D'
AND GLA_AUTO_KEY = XXXX
GROUP BY WOO_AUTO_KEY) GL_DR,

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'C'
AND GLA_AUTO_KEY = XXXX
GROUP BY WOO_AUTO_KEY) GL_CR,

GL_TRANS GLT

WHERE GL_DR.WOO_AUTO_KEY = GLT.WOO_AUTO_KEY
AND GL_CR.WOO_AUTO_KEY = GLT.WOO_AUTO_KEY

GROUP BY GLT.WOO_AUTO_KEY
