SELECT 
WOO.SI_NUMBER WO_NUMBER,
WOO.WO_DISP,
NVL(MAX(WIP_ACCT1.SUM_SUBLEDGER), 0) SUBLEDGER_ ACCT1,
NVL(MAX(WIP_ACCT2.SUM_SUBLEDGER), 0) SUBLEDGER_ ACCT2,
(NVL(MAX(GL_DR.SUM_AMOUNT), 0) - NVL(MAX(GL_CR.SUM_AMOUNT),0)) GL_WIP_ ACCT1, 
(NVL(MAX(GL_DR2.SUM_AMOUNT), 0) - NVL(MAX(GL_CR2.SUM_AMOUNT),0)) GL_WIP_ ACCT2,  
((NVL(MAX(GL_DR.SUM_AMOUNT), 0) - NVL(MAX(GL_CR.SUM_AMOUNT),0)) - NVL(MAX(WIP_ ACCT1.SUM_SUBLEDGER), 0)) VAR_ ACCT1,
((NVL(MAX(GL_DR2.SUM_AMOUNT), 0) - NVL(MAX(GL_CR2.SUM_AMOUNT),0)) - NVL(MAX(WIP_ ACCT2.SUM_SUBLEDGER), 0)) VAR_ ACCT2     

FROM

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'D'
AND GLA_AUTO_KEY = XXXXX
GROUP BY WOO_AUTO_KEY) GL_DR,

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'C'
AND GLA_AUTO_KEY = XXXXX
GROUP BY WOO_AUTO_KEY) GL_CR,

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'D'
AND GLA_AUTO_KEY = YYYYY
GROUP BY WOO_AUTO_KEY) GL_DR2,

(SELECT SUM(AMOUNT) SUM_AMOUNT, WOO_AUTO_KEY
FROM GL_TRANS
WHERE TRAN_TYPE = 'C'
AND GLA_AUTO_KEY = YYYYY
GROUP BY WOO_AUTO_KEY) GL_CR2,

(SELECT MAX(WIP_REMAINING) SUM_SUBLEDGER, TOP_SI_NUMBER
FROM VIEW_WIP_VAL_DETAILS 
WHERE GLA_AUTO_KEY = XXXXX
GROUP BY TOP_SI_NUMBER) WIP_ ACCT1,

(SELECT MAX(WIP_REMAINING) SUM_SUBLEDGER, TOP_SI_NUMBER
FROM VIEW_WIP_VAL_DETAILS 
WHERE GLA_AUTO_KEY = YYYYY
GROUP BY TOP_SI_NUMBER) WIP_ ACCT2,

GL_TRANS GLT, WO_OPERATION WOO, GL_ACCOUNT GLA

WHERE GL_DR.WOO_AUTO_KEY (+)= GLT.WOO_AUTO_KEY
AND GL_CR.WOO_AUTO_KEY (+)= GLT.WOO_AUTO_KEY
AND GL_DR2.WOO_AUTO_KEY (+)= GLT.WOO_AUTO_KEY
AND GL_CR2.WOO_AUTO_KEY (+)= GLT.WOO_AUTO_KEY
AND GLT.WOO_AUTO_KEY = WOO.WOO_AUTO_KEY 
AND WIP_ ACCT1.TOP_SI_NUMBER (+)= WOO.SI_NUMBER
AND WIP_ ACCT2.TOP_SI_NUMBER (+)= WOO.SI_NUMBER

GROUP BY WOO.SI_NUMBER, WOO.WO_DISP
ORDER BY WOO.SI_NUMBER ASC   
